"""initial schema

Revision ID: 94bb03b5d513
Revises: 
Create Date: 2026-09-14 10:18:06.283389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bb03b5d513'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('telegram_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('room', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requester_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_progress', 'done', 'cancelled', name='ticketstatus', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('room_snapshot', sa.String(length=64), nullable=False),
    sa.Column('department_snapshot', sa.String(length=128), nullable=False),
    sa.Column('security_flag', sa.Boolean(), nullable=False),
    sa.Column('source_chat_id', sa.Integer(), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=False),
    sa.Column('queue_message_id', sa.Integer(), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('closed_at IS NULL OR created_at <= closed_at', name='ck_tickets_closed_after_created'),
    sa.ForeignKeyConstraint(['requester_id'], ['employees.telegram_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_tickets_dedup', ['requester_id', 'text_hash', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index('ix_tickets_requester_status', ['requester_id', 'status'], unique=False)

    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('to_requester', 'from_requester', name='messagedirection', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_messages_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_messages_ticket_id'))

    op.drop_table('ticket_messages')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index('ix_tickets_requester_status')
        batch_op.drop_index(batch_op.f('ix_tickets_requester_id'))
        batch_op.drop_index('ix_tickets_dedup')
        batch_op.drop_index(batch_op.f('ix_tickets_created_at'))

    op.drop_table('tickets')
    op.drop_table('employees')
    # ### end Alembic commands ###
